annuaire_service/annuaire_service/urls.py
from django.urls import path
from annuaire_service.annuaire_db import views
app_name = 'annuaire_user'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('search-contact/', views.search_contact, name='search_contact'),

    path('go-contact/', views.go_to_search, name='go_to_search'),
    # Ajout contact 
    path('add-contact', views.add_contact, name='add_contact'),
    # Proumouvoir utilisateur

    path('go-promove/<int:contact_id>/', views.go_to_promove, name='go_to_promove'),
    path('promove-contact/<int:contact_id>/',views.promove_contact,name='promove_contact'),

    path('go-retrograde/<int:contact_id>/', views.go_to_retrograde, name='go_to_retrograde'),
    path('update-contact/<int:contact_id>/', views.update_contact, name='update_contact'),
    # Retrograder utilisateur   
    path('retrograde-contact/<int:contact_id>/', views.retrograde_contact, name='retrograde_contact'),  
    path('delete-contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('accounts/', views.contact, name='account_list') # voir tous les utilisateurs
]

custom_auth_service/custom_auth_service/urls.py
from django.urls import path
from custom_auth_service.auth_db import views

app_name = 'user_auth'
urlpatterns = [
    path('signup/', views.signup, name='register'),
    path('login/', views.user_login, name='auth_login'),
    path('logout/', views.user_logout, name='logout'),
    path('desinscrire-confirm/<int:contact_id>/', views.desinscrire_confirm, name='desinscrire_confirm'),
    path('desinscrire/<int:contact_id>/', views.desinscrire, name='desinscrire'),
    path('contact-detail/<int:contact_id>/', views.contact_detail,  name='contact_detail'),
    path('change-password/<int:contact_id>/', views.change_password, name='change_password'),
    path('update-profil/<int:contact_id>/', views.update_profile, name='update_profil'),
]

securite_projet/urls.py
# securite_projet/urls.py

from django.contrib import admin
from django.urls import path, include  # Ajoutez l'import pour la fonction include
from django.shortcuts import redirect
from django.contrib.auth.decorators import user_passes_test
from custom_auth_service.auth_db.models import User
from custom_auth_service.auth_db.views import user_login
from annuaire_service.annuaire_db.views import home

urlpatterns = [
    path('', lambda request: redirect('user_auth:register')),
    path('admin/', admin.site.urls),
    path('annuaire/', include(('annuaire_service.annuaire_service.urls', 'annuaire_user'), namespace='annuaire_user')),
    path('auth/', include(('custom_auth_service.custom_auth_service.urls', 'user_auth'), namespace='user_auth')),

    path('annuaire/home/',home, name='annuaire_home'),
    path('auth/login/', user_login, name='auth_login'),
]

custom_auth_service/auth_db/models.py
# auth_db/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

class CustomGroup(Group):
    pass

class CustomPermission(Permission):
    pass

class User(AbstractUser):

    class Status(models.IntegerChoices):
        utilisateur = 0
        admin =1
        superadmin =2
    
    groups = models.ManyToManyField(CustomGroup, blank=True, related_name='user_groups')
    user_permissions = models.ManyToManyField(CustomPermission, blank=True, related_name='user_permissions')
    contact_relation = models.ForeignKey('annuaire_db.Contact', on_delete=models.SET_NULL, related_name='contact_account', null=True, blank=True)
    status = models.IntegerField(
        choices = Status.choices, 
        default = Status.utilisateur,
    )
    
    def __str__(self):
        return f'{self.id}'

    class Meta:
        db_table = 'auth_db_user'
        app_label = 'auth_db'
        

class Historique(models.Model):
    ACTION_CHOICES = [
        ('creation', 'Création'),
        ('suppression', 'Suppression'),
        ('mise_a_jour', 'Mise à jour'),
        ('connexion', 'Connexion'),
        ('deconnexion', 'Déconnexion'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentaire = models.CharField(max_length=50, blank=True)
    action= models.CharField(max_length=50, choices=ACTION_CHOICES, blank=True)
    timestamp = models.DateTimeField(auto_now=True)

custom_auth_service/auth_db/views.py
from http.client import HTTPResponse
from django.http import HttpResponseNotFound
from django.utils import timezone
from annuaire_service.annuaire_db.models import Contact
from securite_projet import settings
from .models import Historique, User
from django.db import transaction
import traceback
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, update_session_auth_hash
from django.contrib import messages
from .forms import UserContactEditForm, UserRegistrationForm, LoginForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, login,get_user_model
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import render
from rest_framework import generics
import logging
from django.contrib.auth import get_user_model


logger = logging.getLogger(__name__)

def signup(request):
    form = UserRegistrationForm(request.POST or None)
    
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            print("form est valide ")
            form.save()
            print("inscription effectuée")
        else:
            messages.error(request, 'Fill the form correctly!')

    return render(request, 'register.html', {'form': form})

def user_login(request):
    form = LoginForm(request.POST or None)
    
    if request.method == 'POST' and form.is_valid():
        user = form.save(request)
        
        if user is not None:
            print("Correct username and password")
            print(f'User authenticated: {user.username}')
            next_url = request.GET.get('next', reverse('annuaire_home'))
            print(f"Redirection vers {next_url}")
            return redirect(next_url)

    return render(request, 'login.html', context={'form': form})


def user_logout(request):
    if 'access_token' in request.session:
        del request.session['access_token']
        messages.success(request, 'You have been successfully logged out.')
    return redirect('auth_login')
    

def contact_detail(request, contact_id):
    if 'access_token' in request.session:
        user_id = request.session.get('user_id')
        user = get_object_or_404(User, id=user_id) #   admin ou pas
        contact = get_object_or_404(Contact, id=contact_id)
        data = {
            'id': contact.id,
            'first_name': contact.first_name,
            'last_name': contact.last_name,
            'phone_number': contact.phone_number,
            'email': contact.email,
            "id_user":contact.user_id,
            "status":user.status
        }
        print(data)
        return render(request, 'contact.html',{'data': data})

def status_user(request):
    if 'access_token' in request.session:
        user_id = request.session.get('user_id')
        user = get_object_or_404(User, id=user_id)
        status_data = {
        'id': user.id,
        'status': user.status
        }
        return status_data

def change_password(request,contact_id):
    if 'access_token' in request.session:
        user_id = request.session.get('user_id')
        # Récupérez l'objet User
        contact = get_object_or_404(Contact, id=contact_id)
        data = {
                'id': contact.id,
                'first_name': contact.first_name,
                'last_name': contact.last_name,
                'phone_number': contact.phone_number,
                'email': contact.email,
                "id_user":contact.user_id
            }
        print(data)
        user = get_object_or_404(User.objects.using("auth_db"), id=data["id_user"])      
        if request.method == 'POST':
            form = PasswordChangeForm(user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Your password was successfully updated!')
                historique = Historique.objects.using('auth_db').create(
                    user=user_id,
                    action="mise_a_jour",
                    commentaire="mot de passe",
                    timestamp=timezone.now()
                )
                
                print("historique mis à jour")
                historique.save(using='auth_db')
                return redirect(reverse('annuaire_user:home'))
            else:
                messages.error(request, 'Fill the form correctly!')
        else:
            form = PasswordChangeForm(request.user)
        return render(request, 'update_password.html', {'form': form, 'title': 'Change Password', 'contact_id': contact_id})

def desinscrire_confirm(request, contact_id):
    if 'access_token' in request.session:
        user_id = request.session.get('user_id')
        print("desinscrire confirm")
        try:
            contact_to_delete = get_object_or_404(Contact, id=contact_id)
            user_to_delete=User.objects.using('auth_db').filter(contact_relation=contact_to_delete.id).first()
            print(f"contact to delete : {contact_to_delete} with ID : {contact_id}") 
            print(f"User to delete : {user_to_delete} with ID : {user_id}") 
        except User.DoesNotExist:
            # Handle the case where the user does not exist
            print(f"User with ID {user_id} does not exist.")
            return HttpResponseNotFound("Utilisateur non trouvé")
        return render(request, 'desinscrire.html', {'user_to_delete': user_to_delete,'contact_to_delete': contact_to_delete,'contact_id': contact_to_delete.id})

def desinscrire(request, contact_id):
        if 'access_token' in request.session:
            print("Desinscrire ")

            if request.method == 'POST':
                user_id = request.session.get('user_id')
                contact_to_delete = Contact.objects.using("annuaire_db").get(id=contact_id)
                with transaction.atomic(using='annuaire_db'):
                        # Supprimer l'utilisateur lié manuellement
                        user_to_delete = User.objects.using('auth_db').filter(contact_relation=contact_id).first()
                        if user_to_delete:
                            user_to_delete.delete()

                        # Ensuite, supprimer le contact
                        contact_to_delete.delete()

                        # Enregistrez l'historique de la suppression dans 'auth_db'
                        historique = Historique.objects.using('auth_db').create(
                            user=user_id,
                            action="suppression",
                            commentaire=f"compte de : {contact_id}",
                            timestamp=timezone.now()
                        )

                        print("historique mis à jour")

                        # Déconnectez l'utilisateur
                        user_logout(request)

        return HTTPResponse("Une erreur s'est produite. Veuillez réessayer.")



def update_profile(request, contact_id):
    if 'access_token' in request.session:
        print("update profil ")
        contact = get_object_or_404(Contact, id=contact_id)
        data = {
                'id': contact.id,
                'first_name': contact.first_name,
                'last_name': contact.last_name,
                'phone_number': contact.phone_number,
                'email': contact.email,
                "id_user":contact.user_id
        }
        print(data)
        user_id = get_object_or_404(User, id=data["id_user"])
        if request.method == 'POST':
            combined_form = UserContactEditForm(instance=user_id, data=request.POST)
            if combined_form.is_valid():
                combined_form.save()
                messages.success(request, 'Profile updated successfully.')
                return redirect(reverse('annuaire_user:home'))
            else:
                messages.error(request, 'Please correct the errors below.')
        else:
            combined_form = UserContactEditForm(instance=user_id)

        return render(request, 'profileUpdate.html', {'combined_form': combined_form, 'title': 'Update profil', 'user_id': user_id, 'contact_id':contact_id})

custom_auth_service/auth_db/templates/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'auth_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
    <nav>   
        <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
        <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
      <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>
      <li><a href="{% url 'user_auth:change_password' data.id  %}">Modifier le Mot de Passe</a></li>
    </nav>
</ul>
    <h2>Mon Profil Utilisateur</h2>
    {% if data.status == 1 or request.session.user_id == data.id_user %}
    <nav> 
            <a href="{% url 'user_auth:update_profil' data.id %}" class="btn btn-primary btn-sm">Mettre à jour</a>
            <a href="{% url 'annuaire_user:delete_contact' data.id %}" class="btn btn-danger btn-sm">Supprimer</a> 
            {% if data.status == 1  %}
            <a href="{% url 'annuaire_user:go_to_promove' data.id %}" class="btn btn-primary btn-sm">Promouvoir le contact</a>
            <a href="{% url 'annuaire_user:go_to_retrograde' data.id%}" class="btn btn-primary btn-sm">Rétrograder le contact</a>
            {%endif%}
   
        </nav>
    {%endif%}

   
    <table class="table table-hover table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Id Contact</th>
                <th scope="col">Nom</th>
                <th scope="col">Numéro de téléphone</th>
                <th scope="col">E-mail</th>
                <th scope="col">Id User</th>
            </tr>
        </thead>
        <tbody>
            <tr style="cursor: pointer;">
                <td>{{ data.id }} </td>
                <td>{{ data.first_name }} {{ data.last_name }}</td>
                <td>{{ data.phone_number }}</td>
                <td>{{ data.email }}</td>
                <td>{{ data.id_user }}</td>
            </tr>
        </tbody>
      
    </table>   

    <!-- Ajoutez ici le code pour afficher d'autres détails du contact si nécessaire -->
</body>

custom_auth_service/auth_db/templates/desinscrire.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'auth_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
  <nav>   
    <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
    <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
  <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>
  <li><a href="{% url 'user_auth:change_password' contact_id  %}">Modifier le Mot de Passe</a></li>
  <li><a href="{% url 'user_auth:contact_detail' contact_id %}">Retour</a></li>
</nav>
</ul>
<!-- Formulaire de suppression du compte -->
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Supprimer Le Compte</h2>
      <p>Êtes-vous sûr de vouloir supprimer le compte de {{user_to_delete.first_name}} ? </p>
        <p> Cette action est irréversible.</p>
      <form method="post" action="{% url 'user_auth:desinscrire' contact_id %}" class="mt-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmer la Suppression du Compte</button>
      </form>
    </div>
  </div>
</div>

</body>
</html>

custom_auth_service/auth_db/templates/login.html
<!-- auth_service/templates/login.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'auth_service/css/styles.css' %}">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="text-center my-2">
                    <h2 class="font-semibold"><i class="fas fa-user-circle"></i> Login </h2>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block mt-4">
                        Login
                    </button>
                </form>
                {% if form.errors %}
                    <p class="text-danger mt-2">Username or password is incorrect.</p>
                {% endif %}

                <p class="text-center mt-3 small">
                    Pas de compte ?
                    <a href="{% url 'user_auth:register' %}" class="text-decoration-none">Signup</a>
                </p>
            </div>
        </div>
  </div>

custom_auth_service/auth_db/templates/profileUpdate.html
<!-- auth_service/templates/profileUpdate.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'auth_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
     <ul>
<nav> 
        <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
        <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
        <li class="active"><a href="{% url 'user_auth:change_password' contact_id %}">Modifier le Mot de Passe</a></li>
</nav>      
 </ul>
    <h1>Mise à jour du Profil</h1>

    <form method="post">
        {% csrf_token %}
        {{ combined_form.as_p }}
        <button type="submit">Mettre à jour Profil</button>
    </form>
</body>
</html>

custom_auth_service/auth_db/templates/register.html
<!-- auth_service/templates/register.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ANNUAIRE</title>

    <link rel="stylesheet" href="{% static 'auth_service/css/styles.css' %}">
</head>
<body>
    <H1>ANNUAIRE</H1>

    <h1>Register</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Inscription</button>
    </form>

    <p>Déjà un compte ? <a href="{% url 'auth_login' %}">Connexion</a></p>
</body>
</html>

custom_auth_service/auth_db/templates/update_password.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Modification du Mot de Passe</title>
 <link rel="stylesheet" href="{% static 'auth_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <link rel="stylesheet" href="{% static 'AccountsApp/css/index.css' %}">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
  <ul>
<nav> 

      <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
    <li><a href="{% url 'user_auth:contact_detail' contact_id %}">Mon Profil</a></li>
  
</nav> 
 </ul>
<!-- Formulaire de modification du mot de passe -->
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Modification du Mot de Passe</h2>
      <form method="post" action="{% url 'user_auth:change_password' contact_id %}" class="mt-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Modifier le Mot de Passe</button>
      </form>
    </div>
  </div>
</div>

</body>
</html>