annuaire_service/annuaire_service/urls.py
from django.urls import path
from annuaire_service.annuaire_db import views
app_name = 'annuaire_user'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('search-contact/', views.search_contact, name='search_contact'),

    path('go-contact/', views.go_to_search, name='go_to_search'),
    # Ajout contact 
    path('add-contact', views.add_contact, name='add_contact'),
    # Proumouvoir utilisateur

    path('go-promove/<int:contact_id>/', views.go_to_promove, name='go_to_promove'),
    path('promove-contact/<int:contact_id>/',views.promove_contact,name='promove_contact'),

    path('go-retrograde/<int:contact_id>/', views.go_to_retrograde, name='go_to_retrograde'),
    path('update-contact/<int:contact_id>/', views.update_contact, name='update_contact'),
    # Retrograder utilisateur   
    path('retrograde-contact/<int:contact_id>/', views.retrograde_contact, name='retrograde_contact'),  
    path('delete-contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('accounts/', views.contact, name='account_list') # voir tous les utilisateurs
]

custom_auth_service/custom_auth_service/urls.py
from django.urls import path
from custom_auth_service.auth_db import views

app_name = 'user_auth'
urlpatterns = [
    path('signup/', views.signup, name='register'),
    path('login/', views.user_login, name='auth_login'),
    path('logout/', views.user_logout, name='logout'),
    path('desinscrire-confirm/<int:contact_id>/', views.desinscrire_confirm, name='desinscrire_confirm'),
    path('desinscrire/<int:contact_id>/', views.desinscrire, name='desinscrire'),
    path('contact-detail/<int:contact_id>/', views.contact_detail,  name='contact_detail'),
    path('change-password/<int:contact_id>/', views.change_password, name='change_password'),
    path('update-profil/<int:contact_id>/', views.update_profile, name='update_profil'),
]

securite_projet/urls.py
# securite_projet/urls.py

from django.contrib import admin
from django.urls import path, include  # Ajoutez l'import pour la fonction include
from django.shortcuts import redirect
from django.contrib.auth.decorators import user_passes_test
from custom_auth_service.auth_db.models import User
from custom_auth_service.auth_db.views import user_login
from annuaire_service.annuaire_db.views import home

urlpatterns = [
    path('', lambda request: redirect('user_auth:register')),
    path('admin/', admin.site.urls),
    path('annuaire/', include(('annuaire_service.annuaire_service.urls', 'annuaire_user'), namespace='annuaire_user')),
    path('auth/', include(('custom_auth_service.custom_auth_service.urls', 'user_auth'), namespace='user_auth')),

    path('annuaire/home/',home, name='annuaire_home'),
    path('auth/login/', user_login, name='auth_login'),
]

annuaire_service/annuaire_db/models.py
from django.db import models

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=10, blank=True)
    email = models.EmailField(blank=True)
    user_id = models.BigIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.id}"
    
    class Meta:
        db_table = 'annuaire_db_contact'
        app_label = 'annuaire_db'
        

annuaire_service/annuaire_db/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=10, required=False)  
    email = forms.CharField(max_length=100, required=True) 
    first_name = forms.CharField(max_length=50, required=True) 
    last_name = forms.CharField(max_length=50, required=True) 

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'phone_number', 'email']

    def save(self, commit=True):
        self.full_clean()
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')
        telephone = cleaned_data.get('phone_number')

        if commit:
            # Créer le contact sans spécifier l'utilisateur
            contact = Contact.objects.using('annuaire_db').create()

            # Mettre à jour les champs du contact
            contact.last_name = last_name
            contact.email = email
            contact.phone_number = telephone
            contact.first_name = first_name

            # Si la requête contient un utilisateur, l'associer au contact
            if hasattr(self, 'request') and hasattr(self.request, 'user'):
                contact.user = self.request.user

            # Sauvegarder le contact dans la base de données annuaire_db
            contact.save(using='annuaire_db')

        return contact

annuaire_service/annuaire_db/views.py
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from custom_auth_service.auth_db.forms import AddContactForm
from custom_auth_service.auth_db.models import User
from custom_auth_service.auth_db.views import status_user
from .models import Contact

import io
from django.http import HttpResponseForbidden
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from .forms import ContactForm
from django.db.models import Count, Q  # Ajout de Q pour les requêtes complexes


def add_contact(request):
   if 'access_token' in request.session:
        form = AddContactForm(request.POST or None)
    
        if request.method == 'POST':
            form = AddContactForm(request.POST)
            if form.is_valid():
                print("form est valide ")
                form.save()
                print("inscription effectuée")
        else:
            messages.error(request, 'Fill the form correctly!')
       
        return render(request, 'create_contact.html', {'form': form})

def home(request):
    print("fonction home")
    if 'access_token' in request.session:
        print("Bienvenue sur la page d'accueil ")
        user_id = request.session.get('user_id')
        print("user id",user_id)
        user_status_data = status_user(request) 
        if user_id:
            contacts = Contact.objects.using('annuaire_db').filter(user_id=user_id)
            context = {'contacts': contacts, 'user_status': user_status_data}
            print("retour",context)
            return render(request, 'index.html', context)
        else:
            return HttpResponse("Erreur d'authentification")
    else:
        print("pas authentifié depuis la fonction home ")
        # Gérez le cas où l'utilisateur n'est pas connecté
        return redirect('auth_login')
   
def go_to_retrograde(request,contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    user=User.objects.using('auth_db').filter(contact_relation=contact.id).first()
    data={
        'last_name':contact.last_name,
        'first_name':contact.first_name,
        'contact_id':contact.id,
        'user_id':user.id
    }
    return render(request, 'retrograde.html',{'result':data})
    
def retrograde_contact(request, contact_id):
    if 'access_token' in request.session:
        user_id = request.session.get('user_id')
        user_admin =User.objects.using('auth_db').get(id=user_id)
        contact = get_object_or_404(Contact, id=contact_id)
        user=User.objects.using('auth_db').filter(contact_relation=contact.id).first()
        print("User ID:{user.id} ")

        if user_admin.status == 2 or user_admin.status == 1:
            print("la personne est un admin")
                # Vous pouvez personnaliser cette condition en fonction de vos besoins
            if user.status == 1: # RETROGRADE ADMIN VERS UTILISATEUR
                if request.method == 'POST':
                    print("l'utilisateur est un admin ")
                    user.status = 0
                    user.save()
                    messages.success(request, f'User {user.username} promoted to Admin.')
                else:
                    messages.warning(request, 'You can only promote Utilisateur users.')
                    return redirect(reverse('annuaire_user:home'))    
        else:
            messages.warning(request, 'You are not authorized to perform this action.')
            return HttpResponseForbidden()
    
def go_to_promove(request,contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    user=User.objects.using('auth_db').filter(contact_relation=contact.id).first()
    data={
        'last_name':contact.last_name,
        'first_name':contact.first_name,
        'contact_id':contact.id,
        'user_id':user.id
    }
    return render(request, 'promouvoir.html',{'result':data})
    
def promove_contact(request, contact_id):
    if 'access_token' in request.session:
        user_id = request.session.get('user_id')
        user_admin =User.objects.using('auth_db').get(id=user_id)
        contact = get_object_or_404(Contact, id=contact_id)
        user=User.objects.using('auth_db').filter(contact_relation=contact.id).first()
        print("User ID:{user.id} ")

        if request.method == 'POST':
            if user_admin.status == 2 or user_admin.status == 1:
                # Vous pouvez personnaliser cette condition en fonction de vos besoins
                if user.status == 0: # PROMOTION UTILISATEUR EN ADMIN
                    user.status = 1
                    user.save()
                    messages.success(request, f'User {user.username} promoted to Admin.')
                else:
                    messages.warning(request, 'You can only promote Utilisateur users.')

                return redirect(reverse('annuaire_user:home'))
            else:
                messages.warning(request, 'You are not authorized to perform this action.')
                return HttpResponseForbidden()

def contact(request):
    contacts = Contact.objects.all()
    if 'access_token' in request.session:
       # user_id = request.session.get('user_id')
        user_status_data = status_user(request)  # Appelez la fonction status_user avec l'objet request

        context = {'contacts': contacts, 'user_status': user_status_data}
        print("context de contact list", context)
        return render(request, 'contact-list.html', context)
    else:
        # Gérez le cas où l'utilisateur n'est pas connecté
        return render(request, 'contact-list.html', {'contacts': contacts, 'user_status': None})

def go_to_search(request):
    return render(request, 'search.html')
    
def search_contact(request):
    if 'access_token' in request.session:
        search_query = request.GET.get('query', '')
        user_id = request.session.get('user_id')
        contacts = Contact.objects.filter(user_id=user_id)

        if search_query:
            contacts = contacts.filter(
                first_name__startswith=search_query) | contacts.filter(
                last_name__startswith=search_query) | contacts.filter(
                phone_number__startswith=search_query) | contacts.filter(
                email__startswith=search_query)

        serialized_contacts = []
        for contact in contacts:
            serialized_contacts.append({
                'id': contact.id,
                'first_name': contact.first_name,
                'last_name': contact.last_name,
                'phone_number': contact.phone_number,
                'email': contact.email
            })
        print("reponse:",serialized_contacts)
        return render(request, 'search.html',{'contacts': serialized_contacts})

def update_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    account = request.user.account

    if contact.account != request.user.account:
        messages.warning(request, 'You are not authorized to do this.')
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ContactForm(instance=contact)

    return render(request, 'update.html', {'form': form, 'title': 'Update Contact', 'account': account})

def delete_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)
    account = request.user.account

    if contact.account != request.user.account:
        messages.warning(request, 'You are not authorized to do this.')
        return HttpResponseForbidden()

    if request.method == 'POST':
        contact.delete()
        messages.success(request, 'Contact deleted successfully.')
        return redirect('home')

    return render(request, 'delete_contact.html', {'contact': contact, 'account': account})

annuaire_service/annuaire_db/templates/contact-list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
    {% if status_data %}
        <p>Statut : {{ status_data.status }}</p>
    {% endif %}
    <nav>   
        
        <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
        <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
      <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>
    </nav>
</ul>
<div class="container">
    <h2>Liste des utilisateurs</h2>
    
            <table class="table table-hover table-dark table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Numéro de téléphone</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Status</th>
                        <th scope="col"> Actions</th>
                    </tr>
                </thead>
                <tbody>

            {% for contact in contacts %}
                    <tr style="cursor: pointer;">
                        <td>{{ contact.id }} </td>
                        <td>{{ contact.first_name }} {{ contact.last_name }}</td>
                        <td>{{ contact.phone_number }}</td>
                        <td>{{ contact.email }}</td>
                        <td>{{ user_status.status }}</td>
                        <td> 
                            <a href="{% url 'user_auth:contact_detail' contact.id %}" class="btn btn-primary btn-sm">Voir</a>         
                            {% if user_status.status == 1 %}
                             <a href="{% url 'annuaire_user:update_contact' contact.id %}" class="btn btn-primary btn-sm">Mettre à jour</a>
                            <a href="{% url 'annuaire_user:delete_contact' contact.id %}" class="btn btn-danger btn-sm">Supprimer</a> 
                            <a href="{% url 'annuaire_user:go_to_promove' contact.id %}" class="btn btn-primary btn-sm">Promouvoir le contact</a>
                            <a href="{% url 'annuaire_user:go_to_retrograde' contact.id%}" class="btn btn-primary btn-sm">Rétrograder le contact</a>
                            {%endif%}
                        </td>
                    </tr>

              {%endfor%}
                </tbody>
            </table>
</div>
</body>

annuaire_service/annuaire_db/templates/create_contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
    <nav>   
        <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
        <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
      <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>
    </nav>
</ul>
<div class="container">
    
    <h1 class="text-center">Créer un Contact</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Enregistrer Contact</button>
            </form>
            <!-- Ajoutez ici le code pour afficher d'autres détails du contact si nécessaire -->

            <a href="{% url 'annuaire_user:home' %}" class="btn btn-primary mt-3">Retour à la page d'accueil</a>
        </div>
    </div>
</div></body>

annuaire_service/annuaire_db/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
    <nav>   
      {% for contact in contacts %}
 
        <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
        <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>

        <li><a href="{% url 'user_auth:contact_detail' contact.id %}">Mon profil</a></li>
      <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>
      {%endfor%}

    </nav>
</ul>
 <!-- Liste des contacts -->
 <div class="container-fluid">
  {%for contact in contacts %}
    <div class="row">
      <div class="col-md-9 col-sm-12">BIENVENUE {{contact.first_name}} {{contact.last_name}} DANS L'APPLICATION ANNUAIRE </div>
            <a href="{% url 'annuaire_user:account_list' %}" class="btn btn-primary btn-sm">Liste des contacts </a>
    </div>
  {%endfor%}
 </div>

</body>
</html>

annuaire_service/annuaire_db/templates/promouvoir.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
    <nav>   

          <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
          <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
        <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>

      </nav>
</ul>

    <h1>Promouvoir l'utilisateur</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>Êtes-vous sûr de vouloir promouvoir {{result.last_name}} {{result.first_name}} en Admin?</p>
    <form method="post" action="{% url 'annuaire_user:promove_contact' result.contact_id %}">
        {% csrf_token %}
        <button type="submit">Promouvoir</button>
        <button href="{% url 'annuaire_user:home' %}" class="btn btn-primary btn-sm">Annuler</button>
    </form>
</body>
</html>

annuaire_service/annuaire_db/templates/retrograde.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>
<ul>
    <nav>   

          <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
          <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
        <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>

      </nav>
</ul>

    <h1>Retrograde l'utilisateur</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>Êtes-vous sûr de vouloir retrograde {{result.last_name}} {{result.first_name}} en Admin?</p>
    <form method="post" action="{% url 'annuaire_user:retrograde_contact' result.contact_id %}">
        {% csrf_token %}
        <button type="submit">Retrograde</button>
        <button href="{% url 'annuaire_user:home' %}" class="btn btn-primary btn-sm">Annuler</button>
    </form>
</body>
</html>

annuaire_service/annuaire_db/templates/search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>
<body>

<ul>
    <nav>   

          <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
          <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
  
      </nav>
</ul>
<!-- Formulaire de recherche -->
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <form method="get" action="{% url 'annuaire_user:search_contact' %}" class="mt-4">
        <div class="input-group">
          <input type="text" name="query" class="form-control" placeholder="Entrez le nom ou l'e-mail du contact"><br>
          <div class="input-group-append">
            <button type="submit" class="btn btn-primary"> Rechercher </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Résultats de la recherche -->
<div class="container mt-4">
  <h2>Résultats de la recherche</h2>
  <div class="table-responsive">
    <table class="table table-hover table-dark table-striped">
      <thead>
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Numéro de téléphone</th>
          <th scope="col">E-mail</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for result in contacts %}
        <tr style="cursor: pointer;">
          <td>{{ result.first_name }} {{ result.last_name }}</td>
          <td>{{ result.phone_number }}</td>
          <td>{{ result.email }}</td>
          <td> 
            <a href="{% url 'user_auth:contact_detail' result.id %}" class="btn btn-primary btn-sm">Voir</a>         
            {% if user_status.status == 1 %}
             <a href="{% url 'annuaire_user:update_contact' result.id %}" class="btn btn-primary btn-sm">Mettre à jour</a>
            <a href="{% url 'annuaire_user:delete_contact' result.id %}" class="btn btn-danger btn-sm">Supprimer</a> 
            <a href="{% url 'annuaire_user:promove_contact' result.id%}">Promouvoir le contact</a>
            <a href="{% url 'annuaire_user:retrograde_contact' result.id%}">Rétrograder le contact</a>
            {%endif%}
        </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="4">Aucun résultat trouvé.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- ... -->

</body>
</html>

annuaire_service/annuaire_db/templates/update.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Contacts</title>

 <link rel="stylesheet" href="{% static 'annuaire_service/css/styles.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 <script src="https://kit.fontawesome.com/your-fontawesome-kit.js" crossorigin="anonymous"></script>
</head>

<body>
  <ul>
    <nav>   
        {% for contact in contacts %}

          <li><a href="{% url 'user_auth:logout' %}">Deconnexion</a></li>
          <li><a href="{% url 'annuaire_user:home' %}">Accueil</a></li>
  
          <li><a href="{% url 'user_auth:contact_detail' contact.id %}">Mon profil</a></li>
        <li><a href="{% url 'annuaire_user:go_to_search' %}">Rechercher contact</a></li>
        {%endfor%}
    
      </nav>
</ul>

<!-- Formulaire de mise à jour -->
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Mise à jour du contact</h2>
      <form method="post" action="{% url 'update_contact' contact.id %}" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
          <label for="first_name">Prénom:</label>
          <input type="text" name="first_name" value="{{ contact.first_name }}" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="last_name">Nom:</label>
          <input type="text" name="last_name" value="{{ contact.last_name }}" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="phone_number">Numéro de téléphone:</label>
          <input type="text" name="phone_number" value="{{ contact.phone_number }}" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="email">E-mail:</label>
          <input type="email" name="email" value="{{ contact.email }}" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Mettre à jour</button>
      </form>
    </div>
  </div>
</div>


</body>
</html>